export const LegeerklaeringTekster = {
    "legeerklaering.om-barnet.tittel": "Om barnet",
    "legeerklaering.om-barnet.hjelpetekst": "Hvis barnet ikke har fått fødselsnummer enda skriver du inn barnets fødselsdato.",
    "legeerklaering.om-barnet.navn.paakrevd": "Barnets navn er påkrevd",
    "legeerklaering.om-barnet.ident.label": "Fødselsnummer / D-nummer",
    "legeerklaering.om-barnet.ident.paakrevd": "Barnets norske ID er påkrevd",
    "legeerklaering.om-barnet.foedselsdato.label": "Fødselsdato",
    "legeerklaering.om-barnet.foedselsdato.paakrevd": "Barnets fødselsdato er påkrevd",

    "legeerklaering.legens-vurdering.tittel": "Legens vurdering av barnets tilstand",
    "legeerklaering.legens-vurdering.hjelpetekst": "Her skal du gi din vurdering av barnets nåværende tilstand og funksjonsnivå. I tillegg må du gi en vurdering av forventet tilstand i perioden barnet har behov for tilsyn og pleie.",
    "legeerklaering.legens-vurdering.les-mer.tittel": "Beskrivelse av barnets medisinske tilstand og funksjonsnivå",
    "legeerklaering.legens-vurdering.les-mer.tekst": "1. Beskriv barnets medisinske tilstand og funksjonsnivå. Gi en vurdering av behovet for kontinuerlig tilsyn og pleie, samt sykdomsutvikling og prognose. 2. Gi en vurdering av om det er behov én eller to personer samtidig for å pleie og/eller ha tilsynmed barnet når barnet er hjemme.Merk: Hvis pasienten er over 18 må du gi en vurdering av om pasienten er utviklingshemmet og svært alvorlig eller livstruende syk.",
    "legeerklaering.legens-vurdering.label": "Vurdering av barnets tilstand",
    "legeerklaering.legens-vurdering.paakrevd": "Legens vurdering er påkrevd",

    "legeerklaering.diagnose.tittel": "Diagnose",
    "legeerklaering.diagnose.hjelpetekst": "Benytt kodene fra ICD-10 hvis det er satt en diagnose. Hvis barnet er under utredning og det ikke er fastsatt noen diagnose trenger du ikke skrive noe her.",
    "legeerklaering.diagnose.hoveddiagnose.label": "Hoveddiagnosekode",
    "legeerklaering.diagnose.hoveddiagnose.paakrevd": "Hoveddiagnosekode er påkrevd",
    "legeerklaering.diagnose.bidiagnoser.label": "Bidiagnose(r)",
    "legeerklaering.diagnose.bidiagnoser.paakrevd": "Bidiagnose(r) er påkrevd",

    "legeerklaering.tilsyn-varighet.tittel": "Forventet varighet på tilsyns- og pleiebehovet",
    "legeerklaering.tilsyn-varighet.hjelpetekst": "Her skal du sette en dato på hvor langt fram i tid du forventer at barnet har behov for kontinuerlig tilsyn og pleie. Hvis du er usikker på varigheten setter du en dato så langt frem i tid som du er sikker på per nå.",
    "legeerklaering.tilsyn-varighet.fom.label": "Fra",
    "legeerklaering.tilsyn-varighet.fom.paakrevd": "Fra dato er påkrevd",
    "legeerklaering.tilsyn-varighet.tom.label": "Til",
    "legeerklaering.tilsyn-varighet.tom.paakrevd": "Til dato er påkrevd",

    "legeerklaering.innleggelse-varighet.tittel": "Perioder for innleggelser på helseinstitusjon",
    "legeerklaering.innleggelse-varighet.fom.label": "Fra",
    "legeerklaering.innleggelse-varighet.fom.paakrevd": "Fra dato er påkrevd",
    "legeerklaering.innleggelse-varighet.tom.label": "Til",
    "legeerklaering.innleggelse-varighet.tom.paakrevd": "Til dato er påkrevd",

    "legeerklaering.om-legen.tittel": "Opplysninger om legen",
    "legeerklaering.om-legen.navn.paakrevd": "Legens navn er påkrevd",
    "legeerklaering.om-legen.hrp-nummer.label": "HRP-nummer",
    "legeerklaering.om-legen.hrp-nummer.paakrevd": "Legens HRP-nummer er påkrevd",

    "legeerklaering.om-sykuset.tittel": "Opplysninger om sykehuset",
    "legeerklaering.om-sykuset.navn.paakrevd": "Sykehusets navn er påkrevd",
    "legeerklaering.om-sykuset.tlf.label": "Telefonnummer",
    "legeerklaering.om-sykuset.tlf.paakrevd": "Sykehusets telefonnummer er påkrevd",
    "legeerklaering.om-sykuset.gateadresse.label": "Gateadresse",
    "legeerklaering.om-sykuset.gateadresse.paakrevd": "Sykehusets gateadresse er påkrevd",
    "legeerklaering.om-sykuset.postnummer.label": "Postnummer",
    "legeerklaering.om-sykuset.postnummer.paakrevd": "Sykehusets postnummer er påkrevd",
    "legeerklaering.om-sykuset.poststed.label": "Poststed",
    "legeerklaering.om-sykuset.poststed.paakrevd": "Sykehusets poststed er påkrevd",

    "legeerklaering.felles.navn.label": "Navn",
}
