export const LegeerklaeringTekster = {
    "legeerklaering.om-barnet.tittel": "Om barnet",
    "legeerklaering.om-barnet.hjelpetekst": "Hvis barnet ikke har fått fødselsnummer enda skriver du inn barnets fødselsdato.",
    "legeerklaering.om-barnet.navn.paakrevd": "Barnets navn er påkrevd",
    "legeerklaering.om-barnet.ident.label": "Fødselsnummer / D-nummer",
    "legeerklaering.om-barnet.ident.paakrevd": "Barnets norske ID er påkrevd",
    "legeerklaering.om-barnet.foedselsdato.label": "Fødselsdato",
    "legeerklaering.om-barnet.foedselsdato.paakrevd": "Barnets fødselsdato er påkrevd",

    "legeerklaering.legens-vurdering.barn.tittel": "Vurdering av barnets tilstand",
    "legeerklaering.legens-vurdering.barn.les-mer.tittel": "Hva skal vurderingen inneholde?",
    "legeerklaering.legens-vurdering.barn.les-mer.tekst": "Beskriv barnets medisinske tilstand og funksjonsnivå. Vurder behovet for kontinuerlig tilsyn og pleie, samt sykdomsutvikling og prognose.",
    "legeerklaering.legens-vurdering.barn.label": "Vurdering av barnets tilstand",
    "legeerklaering.legens-vurdering.barn.paakrevd": "Legens vurdering er påkrevd",

    "legeerklaering.legens-vurdering.omsorgsperson.tittel": "Vurdering av en eller to omsorgspersoner",
    "legeerklaering.legens-vurdering.omsorgsperson.les-mer.tittel": "Hva skal vurderingen inneholde?",
    "legeerklaering.legens-vurdering.omsorgsperson.les-mer.tekst": "Vurder om det er behov én eller to personer samtidig for å pleie og/eller ha tilsyn med barnet når barnet er hjemme.",
    "legeerklaering.legens-vurdering.omsorgsperson.label": "Vurdering av en eller to omsorgspersoner",
    "legeerklaering.legens-vurdering.omsorgsperson.paakrevd": "Legens vurdering av omsorgspersoner er påkrevd",

    "legeerklaering.diagnose.tittel": "Diagnose",
    "legeerklaering.diagnose.hjelpetekst.tittel": "Les mer om diagnosekoder",
    "legeerklaering.diagnose.hjelpetekst": "Bruk diagnosekode fra ICD-10 hvis diagnose er satt. Hvis barnet er under utredning og det ikke er fastsatt noen diagnose trenger du ikke fylle ut dette.",
    "legeerklaering.diagnose.hoveddiagnose.label": "Hoveddiagnosekode",
    "legeerklaering.diagnose.hoveddiagnose.paakrevd": "Hoveddiagnose er påkrevd",
    "legeerklaering.diagnose.bidiagnoser.label": "Bidiagnose(r)",
    "legeerklaering.diagnose.bidiagnoser.paakrevd": "Bidiagnose(r) er påkrevd",

    "legeerklaering.tilsyn-varighet.tittel": "Forventet varighet på tilsyns- og pleiebehovet",
    "legeerklaering.tilsyn-varighet.hjelpetekst": "Hvis du er usikker på varigheten setter du en dato så langt frem i tid som du er sikker på per nå. Du kan legge inn flere linjer med ulike perioder ved behov.",
    "legeerklaering.tilsyn-varighet.hjelpetekst.tittel": "Periode(r) du forventer at barnet har behov for kontinuerlig tilsyn og pleie.",
    "legeerklaering.tilsyn-varighet.fom.label": "Fra",
    "legeerklaering.tilsyn-varighet.fom.paakrevd": "Fra dato er påkrevd",
    "legeerklaering.tilsyn-varighet.tom.label": "Til",
    "legeerklaering.tilsyn-varighet.tom.paakrevd": "Til dato er påkrevd",

    "legeerklaering.innleggelse-varighet.tittel": "Perioder for innleggelser på helseinstitusjon",
    "legeerklaering.innleggelse-varighet.fom.label": "Fra",
    "legeerklaering.innleggelse-varighet.fom.paakrevd": "Fra dato er påkrevd",
    "legeerklaering.innleggelse-varighet.tom.label": "Til",
    "legeerklaering.innleggelse-varighet.tom.paakrevd": "Til dato er påkrevd",

    "legeerklaering.om-legen.tittel": "Opplysninger om legen",
    "legeerklaering.om-legen.navn.paakrevd": "Legens navn er påkrevd",
    "legeerklaering.om-legen.hpr-nummer.label": "HPR-nummer",
    "legeerklaering.om-legen.hpr-nummer.paakrevd": "Legens HPR-nummer er påkrevd",

    "legeerklaering.om-sykehuset.tittel": "Opplysninger om sykehuset",
    "legeerklaering.om-sykehuset.navn.paakrevd": "Sykehusets navn er påkrevd",
    "legeerklaering.om-sykehuset.tlf.label": "Telefonnummer",
    "legeerklaering.om-sykehuset.tlf.paakrevd": "Sykehusets telefonnummer er påkrevd",
    "legeerklaering.om-sykehuset.gateadresse.label": "Gateadresse",
    "legeerklaering.om-sykehuset.gateadresse.paakrevd": "Sykehusets gateadresse er påkrevd",
    "legeerklaering.om-sykehuset.postnummer.label": "Postnummer",
    "legeerklaering.om-sykehuset.postnummer.paakrevd": "Sykehusets postnummer er påkrevd",
    "legeerklaering.om-sykehuset.poststed.label": "Poststed",
    "legeerklaering.om-sykehuset.poststed.paakrevd": "Sykehusets poststed er påkrevd",

    "legeerklaering.felles.navn.label": "Navn",
}
